using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Sirenix.OdinInspector;

namespace ProtoRTS.Game
{
	
	/// <summary>
	/// Attack move is unique, because it is generated by BehaviorTable itself when
	/// GUB_Attack and GUB_Move exists
	/// </summary>
	/// 

	public class GUB_AttackMove : GameUnitBehavior
	{

		private void Start()
		{
			
		}

		private void Update()
		{
			
		}
		
		private void OnEnable()
		{
			
		}
	}
}